DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS pages;

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  genre TEXT NOT NULL
)

CREATE TABLE pages (
  id BIGINT GENERATED ALWAYS ALWAYS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  book_id BIGINT REFERENCES books(id)
)